##############################################################################
##############################################################################
######            Hyperparameters, Conditions and Constants             ######
##############################################################################
##############################################################################

##################################
[General]

verbose = False
Number of time steps: 1000000
Number of Crossings : 2
Distribution Outputs = test_dist.dat

##################################

##################################
[Model_Selection]

Model: 2

##################################

##################################
[Hyperparameter]

Number of Axions: 1000

Dimension: 1 

a0: 1
sigma_a: 0.1

b0: 1
sigma_b: 0.1

mmin=-10
mmax=0
kmin=-9
kmax=0


s1: 0.1
s2: 1.5
##################################

##################################
[Initial Conditions]

phi_in_range: 3.141592653589793
phidot_in: 0
a_in: 0.00000001
t_in: 0
t_fi: 1
##################################

##################################
[Physical Constants]

rho_critical: 3.0
rho_matter_0: 0.81
rho_radiation_0: 0.00027138
rho_lambda: 2.19
M_pl: 2.435*10**27
##################################
